# Generated by Django 3.1.4 on 2020-12-12 16:41

import builtins
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('tsync_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentInfo',
            fields=[
                ('tsync_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=14)),
                ('full_address', models.CharField(max_length=512)),
                ('name_of_university', models.CharField(max_length=256)),
                ('graduation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2020)])),
                ('cgpa', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('experience_in_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_work_place_name', models.CharField(max_length=256)),
                ('applying_in', models.CharField(max_length=14)),
                ('expected_salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15000), django.core.validators.MaxValueValidator(60000)])),
                ('field_buzz_reference', models.CharField(max_length=256)),
                ('github_project_url', models.CharField(max_length=256)),
                ('on_spot_update_time', models.DateTimeField(auto_now=True)),
                ('on_spot_creation_time', models.DateTimeField(auto_now_add=True)),
                ('cv_file', models.ForeignKey(on_delete=builtins.callable, to='information.file')),
            ],
        ),
    ]
